### PR TITLE
Fix users (tech & requester) not being deleted during escalation

### PR DESCRIPTION
**Pull request by RomainLvr**
Related ticket : 33695

Continuation of this PR : #212 

These two parameters in the configuration allow you to remove users from the actors in a ticket after an escalation. But this feature was no longer working.

image
image

### CODE REVIEW

**Review by AdrienClairembault — APPROVED** [review]

**Review by Rom1-B — APPROVED** [review]

**Comment by andrepetinga** [comment]
Hello @RomainLvr 
Just tested this fix.

Yes, the technician is removed when I use "Escalate button" and the "Up arrow" (escalation history). But when I search for a group on the "Assigned to" textbox, the technician is not removed.

In addition: If I press the "Associate myself button", I get errors on the php-errors.log:

`[2024-07-17 14:53:34] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "assign" in .../glpi/marketplace/escalade/inc/ticket.class.php at line 108
  Backtrace :
  marketplace/escalade/hook.php:433                  PluginEscaladeTicket::pre_item_update()
  src/Plugin.php:1680                                plugin_escalade_pre_item_update()
  src/CommonDBTM.php:1610                            Plugin::doHook()
  front/ticket.form.php:210                          CommonDBTM->update()
  public/index.php:82                                require()

[2024-07-17 14:53:34] glpiphplog.WARNING:   *** PHP Warning (2): foreach() argument must be of type array|object, null given in .../glpi/marketplace/escalade/inc/ticket.class.php at line 108
  Backtrace :
  marketplace/escalade/hook.php:433                  PluginEscaladeTicket::pre_item_update()
  src/Plugin.php:1680                                plugin_escalade_pre_item_update()
  src/CommonDBTM.php:1610                            Plugin::doHook()
  front/ticket.form.php:210                          CommonDBTM->update()
  public/index.php:82                                require()

[2024-07-17 14:53:34] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in .../glpi/marketplace/escalade/inc/ticket.class.php at line 579
  Backtrace :
  marketplace/escalade/inc/ticket.class.php:643      PluginEscaladeTicket::removeAssignUsers()
  marketplace/escalade/hook.php:482                  PluginEscaladeTicket::item_add_user()
  src/Plugin.php:1680                                plugin_escalade_item_add_user()
  src/CommonDBTM.php:1389                            Plugin::doHook()
  src/CommonITILObject.php:1987                      CommonDBTM->add()
  src/Ticket.php:1345                                CommonITILObject->prepareInputForUpdate()
  src/CommonDBTM.php:1612                            Ticket->prepareInputForUpdate()
  front/ticket.form.php:210                          CommonDBTM->update()
  public/index.php:82                                require()`

Let me just say that the last error "Undefined array key "id"" is new, after this patch is applied.
The other 2 errors were already happening -> #218

**Comment by andrepetinga** [comment]
Hello @RomainLvr.
Today I updated to 2.9.8 version, and then apllied 2 fixes: #219 and #212.

Updating my last post (17/07): 

Yes, the technician is removed when I use "Escalate button" and the "Up arrow" (escalation history). But when I search for a group on the "Assigned to" textbox, the technician is not removed.

In addition: If I press the "Associate myself button", on the "Assign to" box, I get **one warning** on the php-errors.log:

``[2024-07-22 12:23:09] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in …/glpi/marketplace/escalade/inc/ticket.class.php at line 580
	  Backtrace :
	  marketplace/escalade/inc/ticket.class.php:644      PluginEscaladeTicket::removeAssignUsers()
	  marketplace/escalade/hook.php:482                  PluginEscaladeTicket::item_add_user()
	  src/Plugin.php:1713                                plugin_escalade_item_add_user()
	  src/CommonDBTM.php:1395                            Plugin::doHook()
	  src/CommonITILObject.php:1987                      CommonDBTM->add()
	  src/Ticket.php:1345                                CommonITILObject->prepareInputForUpdate()
	  src/CommonDBTM.php:1618                            Ticket->prepareInputForUpdate()
	  front/ticket.form.php:210                          CommonDBTM->update()
  public/index.php:82                                require()``

Let me just say that the last error "Undefined array key "id"" is new, after this patch is applied.

So 2 warnings are gone. Don't know if it was your last commit or because of the update to 2.9.8 version.

**Comment by Windayz** [comment]
Hi there,
Yes, it fixes everything.
However, from now on, when I climb to a group, the technician doesn't delete himself...

**Comment by Windayz** [comment]
Hello,
I approve for: https://github.com/pluginsGLPI/escalade/issues/199

**Review by Rom1-B — APPROVED** [review]

**Comment by andrepetinga** [comment]
> Hello @RomainLvr. Today I updated to 2.9.8 version, and then apllied 2 fixes: #219 and #212.
> 
> Updating my last post (17/07):
> 
> Yes, the technician is removed when I use "Escalate button" and the "Up arrow" (escalation history). But when I search for a group on the "Assigned to" textbox, the technician is not removed.
> 
> In addition: If I press the "Associate myself button", on the "Assign to" box, I get **one warning** on the php-errors.log:
> 
> image
> 
> Let me just say that the last error "Undefined array key "id"" is new, after this patch is applied.
> 
> So 2 warnings are gone. Don't know if it was your last commit or because of the update to 2.9.8 version.

Hello all.
Today I installed the main version of the 2.9.8 version and problems mentioned above are gone!!!

Thanks all!!

**Pull request merged**
